spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: gxx123456
  application:
    name: test
  mvc:
    locale: zh_CN #初始化语言环境
  messages:
    basename: messages #国际化配置位置

server:
  port: 8081
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9099/eureka/